C     Last change:  BB   19 Nov 2001   10:35 pm
        SUBROUTINE DOIGT(NDEGC,DOIGTE,N,CP)
C..
C...POUR CALCULER LA TABLE DES CP A PARTIR DE LA TABLE DES DOIGTES
C...DOIGTE(NTESSC,N)
C...NTESSC EST LE NB DE DEGRES considérés dans LA TESSITURE
C...NDEGC EST LE DEGRE DANS LA TESSITURE POUR LA NOTE CONSIDEREE.
C...(EX: NDEG=3 POUR LA 3EME NOTE considérée LA TESSITURE)
C...N EST LE NB DE TRONCONS (-1) (Y COMPRIS LE BOUT MORT, TOUJOURS
C...FERME, NON COMPRIS L' EMBOUCHURE, NON COMPRIS LE TROU DU PIED DU
C...TUBE PRINCIPAL).
C...ATTENTION AU TRONCONNEMENT POUR CAUSE DE CHANGEMENT DE PERCE:
C...LES 'TROUS LATERAUX' CORRESPONDANTS NE SONT JAMAIS DEBOUCHES. 
C...
C...LA TABLE DES DOIGTES A L' ALLURE SUIVANTE:
C...    1 1 1 1 . . . 1    (CETTE LIGNE EST POUR LA NOTE LA PLUS GRAVE)
C...    0 1 1 1 . . . 1
C...    0 0 1 . . . . 1    (IL Y A AUTANT DE COLONNES QUE DE TRONCONS
C...    0 0 0 . . . . 1                     IE N) 1=TROU FERME
C...    . . . . . . . 1                           0=TROU OUVERT
C...    . . . . . . . 1
C...    . . . . . . . 1     (LA DERNIERE COLONNE EST POUR LE BOUT MORT)
C...    . . . . . . . 1
C...    . . . . . . . 1    (CETTE LIGNE EST POUR LA NOTE LA PLUS AIGUE)
C...   IL Y A AUTANT DE LIGNES QUE DE NOTES considérées DANS LA TESSITURE, IE NTESS
C...
C...TOUS LES ARGUMENTS SONT EN ENTREE, SAUF CP
C...
        INTEGER*4 DOIGTE
        DIMENSION DOIGTE(60,60)
        DIMENSION CP(1)
        DO 1 I=1,N
1       CP(I)=FLOAT(DOIGTE(NDEGC,I))
c...        WRITE(6,2) (CP(I),DOIGTE(NDEGC,I),I=1,N)
2       FORMAT(' CP=',F10.5,'DOIGTE=',I6)
        RETURN
        END

