C     Last change:  BB    5 Apr 2016    3:27 pm
        SUBROUTINE LIBRTE(MA,KA,FCM,FCP,CLOUT,OMEGA,PENTE,N,A,B
     S,AP,BP,S,SP,K,L,LP,PEMB,WEMB,DMA,DKA,DFCM,DFCP,DCLOUT,
     SCTE,RHOA,SLIB)
C...
C...POUR CALCULER UN CRITERE DE SATISFACTION DISANT QUEL EST LE 
C...CHAMP DE LIBERTE EN FREQUENCE POUR LA NOTE CONSIDEREE.
C...QUAND ON FAIT VARIER UN PARAMETRE DE L'ANCHE (MA,KA,FC,CLOUT),
C...LA FREQUENCE DU SYSTEME ANCHE TUYAU CHANGE D' UNE QUANTITE :
C...D(OMEGA)/OMEGA = - (DIMZ/DPARAMETRE)*DPARAMETRE/(PENTE*OMEGA)
C...OU OMEGA EST LA PULSATION DE RESONANCE, ET PENTE LA PENTE DE
C...LA FONCTION IMZ(OMEGA) AU VOISINAGE DE LA RESONANCE.
C...C' EST CETTE QUANTITE (MOYENNEE QUADRATIQUEMENT SUR LES 5
C...PARAMETRES MA,KA,FCM,FCP,CLOUT) QUI EST CALCULEE SOUS LE NOM 
C...DE SLIB (SEUL ARGUMENT EN SORTIE).
C...
C...LES QUANTITES DMA,DKA,DFCM,DCLOUT SONT LES VARIATIONS RELATIVES
C...DES PARAMETRES MA,KA,FCM,CLOUT QU' ON PEUT REALISER AUTOUR DE
C...LEUR VALEUR NOMINALE. LA QUANTITE DFCP EST UNE VARIATION 
C...ABSOLUE.
C...
        IMPLICIT COMPLEX(T)
        REAL  L,LP,MA,KA
        COMPLEX A,B,AP,BP,K,JC,U,V,FC,ZT,PEMB,WEMB
        DIMENSION A(1),B(1),AP(1),BP(1),K(1),L(1),LP(1),S(1),SP(1)
C...QUELQUES CALCULS PREPARATOIRES:
        JC=(0.,1.)
        U=A(N)+B(N)
        TPPIP=CEXP(JC*K(N)*LP(N))
        TPNP1=CEXP(JC*K(N+1)*L(N+1))
        TEMPO1=AP(N)*TPPIP-BP(N)/TPPIP
        V=(S(N)/S(N+1))*(A(N)-B(N))-(SP(N)/S(N+1))*TEMPO1
        T=(U-V)/(U+V)
        FC=FCM*CEXP(JC*FCP)
        TEMPO2=4.*T/(1./TPNP1-T*TPNP1)**2
        TEMPO3=TEMPO2*JC
        ZT=PEMB/WEMB
C...CALCUL DES DIMZ/DPARAMETRE
C...POUR CALCULER LES DIMZ/DPARAMETRE, ON SE RAPPELLERA QUE
C...Z=ZA + ZT/FC
C...OU FC=FCM* CEXP(JC*FCP) EST LE COUPLAGE A L' ANCHE
C...OU ZA=(MA*OMEGA-KA/OMEGA)/S(N+1)**2 EST L' IMPEDANCE DE
C...L' ANCHE,
C...ET OU ZT =PEMB/WEMB EST L' IMPEDANCE DU TUBE SANS ANCHE.
        DZDMA=OMEGA*DMA*MA/S(N+1)**2
        DZDKA=-DKA*KA/(OMEGA*S(N+1)**2)
        DZDFCM=-AIMAG(ZT/FC)*DFCM
        DZDFCP=-AIMAG(ZT/FC)*DFCP
        DZDDL=(OMEGA*RHOA/S(N+1))*AIMAG(TEMPO3/FC)*DCLOUT*CLOUT
C...
c...        WRITE(6,1) DZDMA,DZDKA,DZDFCM,DZDFCP,DZDDL
1       FORMAT('DZDMA,DZDKA,DZDFCM,DZDFCP,DZDDL =',5E12.4)
C...
        SOMCAR=DZDMA**2+DZDKA**2+DZDFCM**2+DZDFCP**2+DZDDL**2
        SLIB=SQRT(SOMCAR)/(PENTE*OMEGA)
        RETURN
        END

