C     Last change:  BB    5 Apr 2016    3:28 pm
        SUBROUTINE PERCE(N,L,LP0,D0,DL,D0P,DLP,S,SB,SP,DELTA,DELTAP)
C...
C...POUR CALCULER LES CARACTERISTIQUES DE LA PERCE.
C...D0,DL EST LE DIAMETRE DU TRONCON A L' ORIGINE ET A L'
C...EXTREMITE.
C...S EST LA SECTION DU TRONCON A L' ORIGINE DES COORDONNEES.
C...DELTA = (DL-D0)/(D0.L) CARACTERISE LA CONICITE DU TRONCON.
C...DELTA ET S SONT UTILISES DANS LTRANS.
C...COMME D' HABITUDE, LE SUFFIXE P INDIQUE UN TRONCON LATERAL.
C...LES 4 DERNIERS ARGUMENTS SONT EN SORTIE.
C...
        REAL L,LP0
        DIMENSION DELTA(1),DELTAP(1),L(1),LP0(1)        
        DIMENSION D0(1),DL(1),D0P(1),DLP(1),S(1),SP(1)
        PI=3.14159
	SB=PI*DL(1)**2/4.
        DO 1 I=1,N
        S(I)=PI*D0(I)**2/4.
        DELTA(I)=(DL(I)-D0(I))/(D0(I)*L(I))
        IF((D0P(I).LT.1.E-8).OR.(LP0(I).LT.1.E-8))GO TO 2
        SP(I)=PI*D0P(I)**2/4.
        DELTAP(I)=(DLP(I)-D0P(I))/(D0P(I)*LP0(I))
        GO TO 1
C...POUR LES TROUS DE SECTION NULLE, ON PREND DELTAP=0.
2       SP(I)=0.
        DELTAP(I)=0.
1       CONTINUE
        S(N+1)=PI*D0(N+1)**2/4.
        DELTA(N+1)=(DL(N+1)-D0(N+1))/(D0(N+1)*L(N+1))
        RETURN
        END


