C     Last change:  BB    5 Apr 2016    5:06 pm
c...subroutine pertes, fichier perte2 créé le 6 aout 2011 par modif
c...du fichier perte1, qui n'avait pas le bon nombre d'arguments
        SUBROUTINE PERTES(OMEGA,L,A,B,AP,BP,N,K,KP,DELTA,DELTAP,S,SP
     S,RHOA,ZRV,CTE,PUITOT,ZRE,PCR,PCV)
C... 
C...POUR CALCULER LA PARTIE REELLE DE L' IMPEDANCE ZRE
C...ET LES POURCENTAGES RELATIFS DES DIFFERENTES CAUSES DE PERTES.
C...TOUS LES AUTRES ARGUMENTS SONT EN ENTREE.
C...
C...ON NEGLIGE LES PERTES LIEES A LA PROPAGATION DE L'AIR EN MILIEU
C...ILLIMITE DEVANT CELLES LIEES AU TUYAU.
C...
        IMPLICIT COMPLEX(T)
        COMPLEX K,KP,A,B,AP,BP,JC,WEMB
        REAL L
        DIMENSION S(1),SP(1),L(1),A(1),B(1),AP(1),BP(1)
        DIMENSION DELTA(1),DELTAP(1)
        DIMENSION K(1),KP(1)
        JC=(0.,1.)
        TEMPO1=-S(N+1)/(JC*OMEGA*RHOA)
        TEMPO2=JC*K(N+1)-DELTA(N+1)
        TEMPO3=JC*K(N+1)+DELTA(N+1)
        WEMB=TEMPO1*(A(N+1)*TEMPO2-B(N+1)*TEMPO3)
C...WEMB EST LE DEBIT A L' EMBOUCHURE (COMPLEXE)
        DEBIEM=ABS(WEMB)
        FNORM=2./DEBIEM**2
C...FNORM EST LE FACTEUR RELIANT LA PUISSANCE TOTALE DEPENSEE
C... PUITOT A ZRE.
C....
C...SOMMATION SUR TOUTES LES CAUSES POSSIBLES DE DISSIPATION
        PUIVIS=ZRV/FNORM
C...PUIVIS EST LA PUISSANCE PERDUE POUR CAUSE VISCOTHERMIQUE.
        CALL RAYONN(OMEGA,L,A,B,AP,BP,N,K,KP,DELTA,DELTAP,S,SP
     S,RHOA,CTE,PUIRAY)
C...PUIRAY EST LA PUISSANCE PERDUE PAR RAYONNEMENT
        PUITOT=PUIVIS+PUIRAY
C....        WRITE(6,1) PUIVIS,PUIRAY,PUITOT
1       FORMAT(' PUIVIS=',E12.5,'PUIRAY=',E12.5,'PUITOT=',E12.5)
        PCV=PUIVIS/PUITOT
        PCR=PUIRAY/PUITOT
        ZRE=FNORM*PUITOT
        RETURN
        END

