C     Last change:  BB    5 Apr 2016    5:09 pm
        SUBROUTINE RAYONN(OMEGA,L,A,B,AP,BP,N,K,KP,DELTA,DELTAP,S,SP
     S,RHOA,CTE,PUIRAY)
C...POUR CALCULER PUIRAY, PUISSANCE PERDUE PAR RAYONNEMENT A TRAVERS 
C...LES TROUS OUVERTS.
C...PUIRAY=RHOA**2*OMEGA**2*DEB**2/(PI*CTE), OU DEB EST LE DEBIT DU TROU.
C...
C...TOUS LES ARGUMENTS SONT EN ENTREE,SAUF PUIRAY.
C...ON FAIT LA SOMME INCOHERENTE DE LA PUISSANCE RAYONNEE PAR 
C...TOUS LES TROUS.
C...LA PUISSANCE RAYONNEE PAR LES TROUS FERMES EST NULLE, LES DEBITS 
c....ETANT NULS.
C...
        IMPLICIT COMPLEX(T)
        COMPLEX K,KP,WPN,W1,WEMB,A,B,AP,BP,JC
        REAL L
        DIMENSION A(1),B(1),AP(1),BP(1),L(1),K(1),KP(1)
        DIMENSION DELTA(1),DELTAP(1),S(1),SP(1)
        JC=(0.,1.)
        PUIRAY=0.
        FACT=RHOA**2*OMEGA**2/(3.1416*CTE)
        DO 1 I=1,N
        TEMPP1=-SP(I)/(JC*OMEGA*RHOA)
        TEMPP2=JC*KP(I)-DELTAP(I)
        TEMPP3=JC*KP(I)+DELTAP(I)
        WPN=TEMPP1*(AP(I)*TEMPP2-BP(I)*TEMPP3)
C...WPN EST LE DEBIT (COMPLEXE) A L' ORIGINE DU TRONCON LATERAL N.
        DEBIPN=ABS(WPN)
1        PUIRAY=PUIRAY+DEBIPN**2
C...IL FAUT ENCORE AJOUTER LA PUISSANCE RAYONNEE AUX DEUX BOUTS DU c...TUBE:
        TEMPO1=-S(1)/(JC*OMEGA*RHOA)
        TEMPO4=JC*K(1)*L(1)
        TEMPO2=(JC*K(1)+DELTA(1)*(TEMPO4-1.))*EXP(TEMPO4)
        TEMPO3=(JC*K(1)+DELTA(1)*(TEMPO4+1.))*EXP(-TEMPO4)
        W1=TEMPO1*(A(1)*TEMPO2-B(1)*TEMPO3)
        DEBI1=ABS(W1)
        PUIBOUT=DEBI1**2 
C...
        TEMPO1=-S(N+1)/(JC*OMEGA*RHOA)
        TEMPO2=JC*K(N+1)-DELTA(N+1)
        TEMPO3=JC*K(N+1)+DELTA(N+1)
        WEMB=TEMPO1*(A(N+1)*TEMPO2-B(N+1)*TEMPO3)
        DEBIEM=ABS(WEMB)
        PUIEMB=DEBIEM**2
C...       
        PUIRAY=PUIRAY+PUIBOUT+PUIEMB
C...NORMALISATION
        PUIRAY=PUIRAY*FACT
        RETURN
        END

