C     Last change:  B     6 Nov 97    7:19 pm
        SUBROUTINE ZERO(M,AB,OR,NZ,RESU,PENTE)
        DIMENSION AB(1),OR(1),RESU(20),IRESU(20),ZOB(20),IRESUV(20)
        DIMENSION PENTE(20)
C...
C....CETTE SUBROUTINE CALCULE LES ZEROS DE LA FONCTION
C...DEFINIE PAR AB,OR, CES DEUX TABLEAUX ETANT DE DIMENSION M
C...LES ZEROS SE TROUVENT DANS LE TABLEAU RESU
C...NZ EST LE NOMBRE DE ZEROS TROUVES.
C...PENTE EST LE TABLEAU DES PENTES DE LA FONCTION AU NIVEAU DES
C..ZEROS TROUVES.
C...LES ABCISSES DE LA FONCTION DOIVENT ETRE CLASSEES PAR ORDRE
C...CROISSANT DANS AB, MAIS PAS NECESSAIREMENT EQUIDISTANTS.
C..........................................................
C...    WRITE(6,18)
18      FORMAT(' ENTREE DANS LA SUBROUTINE ZERO')
        DO 6 L=1,20
        RESU(L)=0.
        ZOB(L)=0.
        IRESUV(L)=0
6       IRESU(L)=0
        K=1
        IF(OR(1).GT.0.) IAV=1
        IF(OR(1).LT.0.) IAV=-1
        DO 1 I=1,M
        IF(OR(I).GT.0.) IAP=1
        IF(OR(I).LT.0.) IAP=-1
        INDIC=IAP*IAV
        IF(INDIC.GT.0) GO TO 2
        ZOB(K)=OR(I-1)*OR(I)
        IRESU(K)=I-1
C...    WRITE(6,17) K,IRESU(K),ZOB(K)
17      FORMAT(' K=  ',I6,' IRESU=  ',I6,' ZOB=  ',E12.6)
        K=K+1
2       CONTINUE
        IAV=IAP
1       CONTINUE
C...DISCRIMINATION ENTRE LES VRAIS ZEROS ET LES INFINIS AVEC
C...CHANGEMENT DE SIGNE.
        NZC=K-1
C...NZC EST LE NB DE ZEROS CANDIDATS
        DO 16 J=1,NZC
c...       WRITE(6,15) J,ZOB(J)
15      FORMAT(' J=',I6,' ZOB(J)=',E12.5)
16      CONTINUE
        IF(NZC.EQ.1) GO TO 12
        NZCS2=NZC/2
        NZCC=2*NZCS2
C...CALCUL DE LA VALEUR MOYENNE DE OR(I-1)*OR(I)
        ZBAR=0.
        DO 9 N=1,NZCC
9        ZBAR=ZBAR+ZOB(N)/FLOAT(NZCC)
c...        WRITE(6,14) ZBAR
14      FORMAT(' ZBAR=',E12.5)
C...TEST POUR SAVOIR SI ON A AFFAIRE A UN ZERO VRAI OU A UN INFINI
        NZVRAI=0
        ZBSD=ZBAR/10.
        DO 10 N=1,NZC
c....        IF(ZOB(N).LT.ZBSD) GO TO 11
        NZVRAI=NZVRAI+1
        IRESUV(NZVRAI)=IRESU(N)
11      CONTINUE
10      CONTINUE
C... NZVRAI EST LE NOMBRE DE VRAIS ZEROS.
        GO TO 13
12      NZVRAI=1
        IRESUV(1)=IRESU(1)
13      CONTINUE
        WRITE(6,8) NZVRAI
8       FORMAT(' NOMBRE DE ZEROS TROUVES=',I8)
C....LE TABLEAU IRESUV(K) CONTIENT LES ABCISSES I POUR LESQUELLES
C...IL Y A EU CHANGEMENT DE SIGNE DE OR(I) ENTRE I ET I+1.
        NZ=NZVRAI
C....INTERPOLATION
        DO 3 J=1,NZVRAI
        I=IRESUV(J)
        IF(I.EQ.0) GO TO 5
        RESU(J)=(AB(I)*OR(I+1)-AB(I+1)*OR(I))/(OR(I+1)-OR(I))
        PENTE(J)=(OR(I+1)-OR(I))/(AB(I+1)-AB(I))
c...        WRITE(6,4) J,RESU(J)
4       FORMAT(' ZERO N0',I8,' OMEGA=',F10.5)
        WRITE(6,7) IRESU(J),AB(I),AB(I+1),OR(I),OR(I+1)
7       FORMAT(' I=',I6,'AB(I)',F10.1,'AB(I+1)',F10.1,'ORS',2F10.1)
3       CONTINUE
5       RETURN
        END

