function varargout = reeddatabase_export(varargin)
%REEDDATABASE_EXPORT M-file for reeddatabase_export.fig
%      REEDDATABASE_EXPORT, by itself, creates a new REEDDATABASE_EXPORT or raises the existing
%      singleton*.
%
%      H = REEDDATABASE_EXPORT returns the handle to a new REEDDATABASE_EXPORT or the handle to
%      the existing singleton*.
%
%      REEDDATABASE_EXPORT('Property','Value',...) creates a new REEDDATABASE_EXPORT using the
%      given property value pairs. Unrecognized properties are passed via
%      varargin to reeddatabase_export_OpeningFcn.  This calling syntax produces a
%      warning when there is an existing singleton*.
%
%      REEDDATABASE_EXPORT('CALLBACK') and REEDDATABASE_EXPORT('CALLBACK',hObject,...) call the
%      local function named CALLBACK in REEDDATABASE_EXPORT.M with the given input
%      arguments.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% Edit the above text to modify the response to help reeddatabase_export

% Last Modified by GUIDE v2.5 13-Nov-2014 11:12:12

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @reeddatabase_export_OpeningFcn, ...
                   'gui_OutputFcn',  @reeddatabase_export_OutputFcn, ...
                   'gui_LayoutFcn',  @reeddatabase_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
   gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before reeddatabase_export is made visible.
function reeddatabase_export_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   unrecognized PropertyName/PropertyValue pairs from the
%            command line (see VARARGIN)

% Choose default command line output for reeddatabase_export
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);

% UIWAIT makes reeddatabase_export wait for user response (see UIRESUME)
% uiwait(handles.figure1);




% --- Outputs from this function are returned to the command line.
function varargout = reeddatabase_export_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Get default command line output from handles structure
varargout{1} = handles.output;


% --- Executes on button press in B_Open.
function B_Open_Callback(hObject, eventdata, handles)
% hObject    handle to B_Open (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
file = uigetfile('*.mat');
        if ~isequal(file, 0)
           Properties_mat = importdata(file);    
            set(handles.Prop_Mat_Tab,'Data', Properties_mat  );
            set(handles.Pan_reed_data,'Visible','on');
            
            for i = 1:length(Properties_mat(:,1))-1   
            yreed(2*i) = Properties_mat(i,4);    
            yreed(2*i+1) = Properties_mat(i+1,4); 
            xreed(2*i) = sum(Properties_mat(1:i,1)) ;
            xreed(2*i+1) =xreed(2*i) ;
            end
            xreed = [0,xreed(2:end),sum(Properties_mat(:,1)),sum(Properties_mat(:,1))];
            yreed= [Properties_mat(1,4),yreed(2:end),Properties_mat(end,4),0];
            area(handles.Axes_reed,xreed,yreed);            
        end


% --- Executes on button press in B_Select.
function B_Select_Callback(hObject, eventdata, handles)
% hObject    handle to B_Select (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in B_Ok.
function B_Ok_Callback(hObject, eventdata, handles)
% hObject    handle to B_Ok (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


% --- Executes on button press in B_Save.
function B_Save_Callback(hObject, eventdata, handles)
% hObject    handle to B_Save (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
Properties_mat = get(handles.Prop_Mat_Tab,'Data'  )
uisave({'Properties_mat'},'*.mat');


% --- Executes when entered data in editable cell(s) in Prop_Mat_Tab.
function Prop_Mat_Tab_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to Prop_Mat_Tab (see GCBO)
% eventdata  structure with the following fields (see UITABLE)
%	Indices: row and column indices of the cell(s) edited
%	PreviousData: previous data for the cell(s) edited
%	EditData: string(s) entered by the user
%	NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%	Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)
            
            Properties_mat = get(handles.Prop_Mat_Tab,'Data'  );
         if (length(Properties_mat(:,1))-1 >1)
          
          
              
         for i = 1:length(Properties_mat(:,1))-1   
            yreed(2*i) = Properties_mat(i,4);    
            yreed(2*i+1) = Properties_mat(i+1,4); 
            xreed(2*i) = sum(Properties_mat(1:i,1)) ;
            xreed(2*i+1) =xreed(2*i) ;
         end
         
            xreed = [0,xreed(2:end),sum(Properties_mat(:,1)),sum(Properties_mat(:,1))];
            yreed= [Properties_mat(1,4),yreed(2:end),Properties_mat(end,4),0];
         
         else
             xreed = [0,0,sum(Properties_mat(:,1)),sum(Properties_mat(:,1))];
             yreed= [0,Properties_mat(1,4),Properties_mat(end,4),0];
             
         end
         
            area(handles.Axes_reed,xreed,yreed); 


% --- Executes during object creation, after setting all properties.
function figure1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to figure1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called


% --- Executes during object creation, after setting all properties.
function Axes_FFT_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axes_FFT (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: place code in OpeningFcn to populate Axes_FFT
rectangle('Position',[1,2,5,10],'Curvature',[0,0],...
          'FaceColor','r')
      


% --- Executes on button press in Button_Compute.
function Button_Compute_Callback(hObject, eventdata, handles)
% hObject    handle to Button_Compute (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.Pan_Curves, 'Visible', 'on');
matkm( get(handles.Prop_Mat_Tab,'Data'  ) ,handles);


function [Mp,Kp] = matkm(Properties_mat,handles)


syms x  ;
%Properties_mat = [ 4.550*10^-3 , 7800 , 4.259*10^-3 , 0.35*10^-3 , 2.1*10^11 ; 14.850*10^-3 , 7800 , 4.008*10^-3 , 0.2*10^-3 , 2.1*10^11 ; 9*10^-3 , 7800 , 3.699*10^-3 , 0.275*10^-3 , 2.1*10^11 ; 9*10^-3 , 7800 , 3.466*10^-3 , 1.5*10^-3 , 2.1*10^11 ] ; 
% du type [x0 (longeur tron�on ),rho0 (densit� moyenne du troncon) ,b0 (largeur -constante- de l'anche) ,h0 (Epaisseur) ,E0 (Module Young)  ;  xi,rhoi,bi,hi,Ei  ;  xn,rhon,bn,hn,En] 
% Note :
% Rem  :


NDDL =  5;

Sums  =  sum(Properties_mat); 
L = Sums(1) ;


M=zeros(NDDL);
K=zeros(NDDL);

for i= [1: NDDL];
   [Bi,Si] = BL_Sigma(i) ; 
 for j= [1 : NDDL] ;
  [nsection,nparam] = size(Properties_mat) ; 
 [Bj,Sj] = BL_Sigma(j) ; 
  M_ij=0;
  K_ij=0;
  xn = 0;
  xnp1=  Properties_mat(1,1);
  for k=1:nsection  
if k>1
 xn = xnp1;
xnp1= xnp1 + Properties_mat(k,1);
end
kij = double(int((diff(cosh(Bi/L*x)-cos(Bi/L*x)-Si*(sinh(Bi/L*x)-sin(Bi/L*x)),2)*diff(cosh(Bj/L*x)-cos(Bj/L*x)-Sj*(sinh(Bj/L*x)-sin(Bj/L*x)),2)) , xn , xnp1) ); 
 mij = double(int((cosh(Bi/L*x)-cos(Bi/L*x)-Si*(sinh(Bi/L*x)-sin(Bi/L*x)))*(cosh(Bj/L*x)-cos(Bj/L*x)-Sj*(sinh(Bj/L*x)-sin(Bj/L*x))) , xn , xnp1 ));  
K_ij = K_ij + kij*Properties_mat(k,5)*Properties_mat(k,3)*Properties_mat(k,4)^3/12;
M_ij = M_ij + mij*Properties_mat(k,2)*Properties_mat(k,3)*Properties_mat(k,4);
  end

M(i,j) = M_ij ; 
K(i,j)= K_ij;
end
end


Val = eig(K,M) 

Freq= sqrt(Val)./(2*pi)

stem(handles.Axes_FFT,Freq,Val);



function [Bl,sigma] = BL_Sigma(n)
%/ n            : numero du mode ;
%// x      		: [Parametre de la fonction : position longitudinale ou on recheche la déformée modale]
%// Offset 		: [valeur de l'offset du à la déformée statique en x]
%// Bl     		: [Longeur de l'anche : Variable Externe]
%// sigma 	 	: [Longeur de l'anche : Variable Externe]
%// Long_Anche 	: [Longeur de l'anche : Variable Externe]
%// f 			: [variable de sortie de la fonction : donne la valeur de la déformée modale en un point x]
%//----------------------------------------------------------------------------------------------------------

if n < 6

switch n
    case 1
 Bl              = 1.87510407                                     			;%// Coefficient Bl pour calculer les deformée modales
sigma			 = 0.7341                                         			;%// Coefficient sigma pour calculer les deformée modales

case 2 
 
 Bl              = 4.69409113                                     			;%// Coefficient Bl pour calculer les deformée modales
sigma			 = 1.0185                                         			;%// Coefficient sigma pour calculer les deformée modales

case 3 
Bl               = 7.85475744                                     			;%// Coefficient Bl pour calculer les deformée modales
sigma			 = 0.9992                                         			;%// Coefficient sigma pour calculer les deformée modales

 
case 4 
 Bl               = 10.99554073                                     			;%// Coefficient Bl pour calculer les deformée modales
sigma			 = 1                                         			;%// Coefficient sigma pour calculer les deformée modales

case 5 
Bl               = 14.13716839                                     			;%// Coefficient Bl pour calculer les deformée modales
sigma			 = 1                                         			;%// Coefficient sigma pour calculer les deformée modales


end
else
Bl               =   (2*n-1)*pi/2                                  			;%// Coefficient Bl pour calculer les deformée modales
sigma			=    1                                             			;%// Coefficient sigma pour calculer les deformée modales



end

      

function  [Omega_n ]= Pulsa_nat(n) 

[Bl,~]=BL_Sigma(n);
E=B*h^3/12;
Omega_n =(Bl)^2*(E*I/(Roh*A*L^4))^0.5 ;


% --- Executes on button press in pushbutton6.
function pushbutton6_Callback(hObject, eventdata, handles)
% hObject    handle to pushbutton6 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
set(handles.Prop_Mat_Tab,'Data', zeros(1,5) );
cla(handles.Axes_reed);
 set(handles.Pan_reed_data,'Visible','on');


% --- Executes during object creation, after setting all properties.
function Pan_reed_data_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Pan_reed_data (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called


% --- Executes during object creation, after setting all properties.
function Axes_reed_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Axes_reed (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: place code in OpeningFcn to populate Axes_reed


% --- Executes during object creation, after setting all properties.
function Prop_Mat_Tab_CreateFcn(hObject, eventdata, handles)
% hObject    handle to Prop_Mat_Tab (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called



function edit1_Callback(hObject, eventdata, handles)
% hObject    handle to edit1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: get(hObject,'String') returns contents of edit1 as text
%        str2double(get(hObject,'String')) returns contents of edit1 as a double


% --- Executes during object creation, after setting all properties.
function edit1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to edit1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called

% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end


% --- Executes when entered data in editable cell(s) in Nbr_troncon.
function Nbr_troncon_CellEditCallback(hObject, eventdata, handles)
% hObject    handle to Nbr_troncon (see GCBO)
% eventdata  structure with the following fields (see UITABLE)
%	Indices: row and column indices of the cell(s) edited
%	PreviousData: previous data for the cell(s) edited
%	EditData: string(s) entered by the user
%	NewData: EditData or its converted form set on the Data property. Empty if Data was not changed
%	Error: error string when failed to convert EditData to appropriate value for Data
% handles    structure with handles and user data (see GUIDATA)

 nbr_trcon = get(handles.Nbr_troncon ,'Data');
set(handles.Prop_Mat_Tab,'Data', zeros(nbr_trcon{1},5) );


% --- Creates and returns a handle to the GUI figure. 
function h1 = reeddatabase_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end
load reeddatabase_export.mat


appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', 198.001831054688, ...
    'taginfo', struct(...
    'figure', 2, ...
    'pushbutton', 7, ...
    'axes', 4, ...
    'uitable', 4, ...
    'uipanel', 4, ...
    'text', 2, ...
    'edit', 2), ...
    'override', 0, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 1, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\Users\zao\Google Drive\labo de zao\anches models\anches\libre\acomdelGUI\reeddatabase_export.m', ...
    'lastFilename', 'C:\Users\zao\Google Drive\labo de zao\anches models\anches\libre\acomdelGUI\reeddatabase.fig');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];
appdata.initTags = struct(...
    'handle', [], ...
    'tag', 'figure1');

h1 = figure(...
'Units','characters',...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Color',[0.941176470588235 0.941176470588235 0.941176470588235],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','Reed Database',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',get(0,'defaultfigurePaperSize'),...
'PaperType',get(0,'defaultfigurePaperType'),...
'Position',[103.8 4.69230769230769 237.4 56.9230769230769],...
'Resize','off',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)reeddatabase_export('figure1_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'HandleVisibility','callback',...
'UserData',[],...
'Tag','figure1',...
'Visible','on');

appdata = [];
appdata.lastValidTag = 'uipanel1';

h2 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontUnits','pixels',...
'FontSize',10.6666666666667,...
'Title',{  'Panel' },...
'Tag','uipanel1',...
'Clipping','on',...
'Position',[17 5.92307692307692 57.2 8.61538461538462],...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'B_Open';

h3 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontUnits','pixels',...
'Callback',@(hObject,eventdata)reeddatabase_export('B_Open_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10.6666666666667,...
'Position',[2.6 2.84615384615384 50.2 1.76923076923077],...
'String','Open Reed Data',...
'Tag','B_Open',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'B_Save';

h4 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontUnits','pixels',...
'Callback',@(hObject,eventdata)reeddatabase_export('B_Save_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10.6666666666667,...
'Position',[2.6 0.769230769230766 50.2 1.76923076923077],...
'String','Save Reed Data',...
'Tag','B_Save',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'pushbutton6';

h5 = uicontrol(...
'Parent',h2,...
'Units','characters',...
'FontUnits','pixels',...
'Callback',@(hObject,eventdata)reeddatabase_export('pushbutton6_Callback',hObject,eventdata,guidata(hObject)),...
'CData',[],...
'FontSize',10.6666666666667,...
'Position',[2.4 4.92307692307693 50.2 1.76923076923077],...
'String','New Reed Data',...
'UserData',[],...
'Tag','pushbutton6',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Pan_Curves';

h6 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontUnits','pixels',...
'FontSize',10.6666666666667,...
'Title',{  'Panel' },...
'Tag','Pan_Curves',...
'UserData',[],...
'Clipping','on',...
'Position',[6.2 19.9230769230769 219.6 36.7692307692308],...
'Visible','off',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Axes_FFT';

h7 = axes(...
'Parent',h6,...
'Units','characters',...
'FontUnits','pixels',...
'Position',[7.6 4.23076923076923 52.6 28.7692307692308],...
'CameraPosition',[3.5 7 70.178344238091],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'DataAspectRatio',get(0,'defaultaxesDataAspectRatio'),...
'DataAspectRatioMode','manual',...
'FontSize',13.3333333333333,...
'LooseInset',[24.31 2.40307692307692 17.765 1.63846153846154],...
'XColor',get(0,'defaultaxesXColor'),...
'XLim',[0 7],...
'XLimMode','manual',...
'YColor',get(0,'defaultaxesYColor'),...
'YLim',[1 13],...
'YLimMode','manual',...
'ZColor',get(0,'defaultaxesZColor'),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)reeddatabase_export('Axes_FFT_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Axes_FFT',...
'UserData',[]);

h8 = get(h7,'title');

set(h8,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[3.46791443850268 13.2085561497326 1.00042425601769],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h9 = get(h7,'xlabel');

set(h9,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[3.46791443850268 0.245989304812834 1.00042425601769],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h10 = get(h7,'ylabel');

set(h10,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.799465240641712 6.95187165775401 1.00042425601769],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h11 = get(h7,'zlabel');

set(h11,...
'Parent',h7,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-3.01336898395722 14.5561497326203 1.00042425601769],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'Pan_reed_data';

h12 = uipanel(...
'Parent',h1,...
'Units','characters',...
'FontUnits','pixels',...
'FontSize',10.6666666666667,...
'Title',{  'Panel' },...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)reeddatabase_export('Pan_reed_data_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Pan_reed_data',...
'Clipping','on',...
'Position',[92.6 0.846153846153846 133.6 18.6923076923077],...
'Visible','off');

appdata = [];
appdata.lastValidTag = 'Prop_Mat_Tab';
appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'RowNameTyped' 'ColumnNameTyped' } {  [4 5] [4 5] 'DataExisting' [2 3] {  blanks(0) blanks(0) blanks(0) blanks(0) } {  'Section length' 'Section density' 'Section width' 'Section thickness' 'Young modulus' } } };

h13 = uitable(...
'Parent',h12,...
'Units','characters',...
'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
'CellEditCallback',@(hObject,eventdata)reeddatabase_export('Prop_Mat_Tab_CellEditCallback',hObject,eventdata,guidata(hObject)),...
'ColumnFormat',{  'numeric' 'numeric' 'numeric' 'numeric' 'numeric' },...
'ColumnEditable',mat{1},...
'ColumnName',{  'Section length'; 'Section density'; 'Section width'; 'Section thickness'; 'Young modulus' },...
'ColumnWidth',{  'auto' 'auto' 'auto' 'auto' 'auto' },...
'Data',{  [] [] [] [] []; [] [] [] [] []; [] [] [] [] []; [] [] [] [] [] },...
'Position',[17.8 0.384615384615385 107 9.07692307692308],...
'RearrangeableColumns','on',...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)reeddatabase_export('Prop_Mat_Tab_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'HandleVisibility','off',...
'UserData',[0.00455 0.01485 0.009 0.009 7800 7800 7800 7800 0.004259 0.004008 0.003699 0.003466 0.00035 0.0002 0.000275 0.0015 210000000000 210000000000 210000000000 210000000000],...
'Tag','Prop_Mat_Tab');

appdata = [];
appdata.lastValidTag = 'text1';

h14 = uicontrol(...
'Parent',h12,...
'Units','characters',...
'FontUnits','pixels',...
'FontSize',10.6666666666667,...
'Position',[1.6 7.76923076923077 16.2 1.69230769230769],...
'String','Section number:',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Axes_reed';

h15 = axes(...
'Parent',h12,...
'Units','characters',...
'FontUnits','pixels',...
'Position',[22.8 12 72.2 3.53846153846154],...
'CameraPosition',[0.5 0.5 9.16025403784439],...
'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
'Color',get(0,'defaultaxesColor'),...
'ColorOrder',get(0,'defaultaxesColorOrder'),...
'DataAspectRatio',get(0,'defaultaxesDataAspectRatio'),...
'DataAspectRatioMode','manual',...
'FontSize',13.3333333333333,...
'LooseInset',[24.31 2.40307692307692 17.765 1.63846153846154],...
'XColor',get(0,'defaultaxesXColor'),...
'YColor',get(0,'defaultaxesYColor'),...
'YGrid','on',...
'ZColor',get(0,'defaultaxesZColor'),...
'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)reeddatabase_export('Axes_reed_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
'Tag','Axes_reed',...
'UserData',[]);

h16 = get(h15,'title');

set(h16,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.478260869565215 1.14130434782609 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h17 = get(h15,'xlabel');

set(h17,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[0.478260869565215 -0.510869565217391 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','cap',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h18 = get(h15,'ylabel');

set(h18,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','center',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-0.630434782608697 0.467391304347826 1.00005459937205],...
'Rotation',90,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','bottom',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','on',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

h19 = get(h15,'zlabel');

set(h19,...
'Parent',h15,...
'Units','data',...
'FontUnits','points',...
'BackgroundColor','none',...
'Color',[0 0 0],...
'DisplayName',blanks(0),...
'EdgeColor','none',...
'EraseMode','normal',...
'DVIMode','auto',...
'FontAngle','normal',...
'FontName','Helvetica',...
'FontSize',10,...
'FontWeight','normal',...
'HorizontalAlignment','right',...
'LineStyle','-',...
'LineWidth',0.5,...
'Margin',2,...
'Position',[-16.0217391304348 12.3804347826087 1.00005459937205],...
'Rotation',0,...
'String',blanks(0),...
'Interpreter','tex',...
'VerticalAlignment','middle',...
'ButtonDownFcn',[],...
'CreateFcn', {@local_CreateFcn, [], ''} ,...
'DeleteFcn',[],...
'BusyAction','queue',...
'HandleVisibility','off',...
'HelpTopicKey',blanks(0),...
'HitTest','on',...
'Interruptible','on',...
'SelectionHighlight','on',...
'Serializable','on',...
'Tag',blanks(0),...
'UserData',[],...
'Visible','off',...
'XLimInclude','on',...
'YLimInclude','on',...
'ZLimInclude','on',...
'CLimInclude','on',...
'ALimInclude','on',...
'IncludeRenderer','on',...
'Clipping','off');

appdata = [];
appdata.lastValidTag = 'Button_Compute';

h20 = uicontrol(...
'Parent',h12,...
'Units','characters',...
'FontUnits','pixels',...
'Callback',@(hObject,eventdata)reeddatabase_export('Button_Compute_Callback',hObject,eventdata,guidata(hObject)),...
'FontSize',10.6666666666667,...
'Position',[100 15.3846153846154 31.8 1.76923076923077],...
'String','Compute reed data',...
'Tag','Button_Compute',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

appdata = [];
appdata.lastValidTag = 'Nbr_troncon';
appdata.PropertyMetaData = {  {  'DataPropertyDimension' 'DataPropertyConditionedDimension' 'DataPropertySource' 'BackgroundColorPropertyDimension' 'ColumnNameTyped' 'RowNameTyped' } {  [1 2] [1 2] 'DataExisting' [2 3] {  'Nbr troncon' blanks(0) } {  blanks(0) } } };

h21 = uitable(...
'Parent',h12,...
'Units','characters',...
'BackgroundColor',[1 1 1;0.96078431372549 0.96078431372549 0.96078431372549],...
'CellEditCallback',@(hObject,eventdata)reeddatabase_export('Nbr_troncon_CellEditCallback',hObject,eventdata,guidata(hObject)),...
'ColumnFormat',{  'numeric' 'numeric' },...
'ColumnEditable',mat{2},...
'ColumnName',{  'Nbr troncon'; blanks(0) },...
'ColumnWidth',{  'auto' 0 },...
'Data',{  0 [] },...
'Position',[110.8 10.0769230769231 17 3.23076923076923],...
'RowName',blanks(0),...
'UserData',[],...
'Tag','Nbr_troncon',...
'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   if isa(createfcn,'function_handle')
       createfcn(hObject, eventdata);
   else
       eval(createfcn);
   end
end


% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

gui_StateFields =  {'gui_Name'
    'gui_Singleton'
    'gui_OpeningFcn'
    'gui_OutputFcn'
    'gui_LayoutFcn'
    'gui_Callback'};
gui_Mfile = '';
for i=1:length(gui_StateFields)
    if ~isfield(gui_State, gui_StateFields{i})
        error('MATLAB:gui_mainfcn:FieldNotFound', 'Could not find field %s in the gui_State struct in GUI M-file %s', gui_StateFields{i}, gui_Mfile);
    elseif isequal(gui_StateFields{i}, 'gui_Name')
        gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
    end
end

numargin = length(varargin);

if numargin == 0
    % REEDDATABASE_EXPORT
    % create the GUI only if we are not in the process of loading it
    % already
    gui_Create = true;
elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
    % REEDDATABASE_EXPORT(ACTIVEX,...)
    vin{1} = gui_State.gui_Name;
    vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
    vin{3} = varargin{1};
    vin{4} = varargin{end-1};
    vin{5} = guidata(varargin{1}.Peer);
    feval(vin{:});
    return;
elseif local_isInvokeHGCallback(gui_State, varargin{:})
    % REEDDATABASE_EXPORT('CALLBACK',hObject,eventData,handles,...)
    gui_Create = false;
else
    % REEDDATABASE_EXPORT(...)
    % create the GUI and hand varargin to the openingfcn
    gui_Create = true;
end

if ~gui_Create
    % In design time, we need to mark all components possibly created in
    % the coming callback evaluation as non-serializable. This way, they
    % will not be brought into GUIDE and not be saved in the figure file
    % when running/saving the GUI from GUIDE.
    designEval = false;
    if (numargin>1 && ishghandle(varargin{2}))
        fig = varargin{2};
        while ~isempty(fig) && ~ishghandle(fig,'figure')
            fig = get(fig,'parent');
        end
        
        designEval = isappdata(0,'CreatingGUIDEFigure') || isprop(fig,'__GUIDEFigure');
    end
        
    if designEval
        beforeChildren = findall(fig);
    end
    
    % evaluate the callback now
    varargin{1} = gui_State.gui_Callback;
    if nargout
        [varargout{1:nargout}] = feval(varargin{:});
    else       
        feval(varargin{:});
    end
    
    % Set serializable of objects created in the above callback to off in
    % design time. Need to check whether figure handle is still valid in
    % case the figure is deleted during the callback dispatching.
    if designEval && ishghandle(fig)
        set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
    end
else
    if gui_State.gui_Singleton
        gui_SingletonOpt = 'reuse';
    else
        gui_SingletonOpt = 'new';
    end

    % Check user passing 'visible' P/V pair first so that its value can be
    % used by oepnfig to prevent flickering
    gui_Visible = 'auto';
    gui_VisibleInput = '';
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        % Recognize 'visible' P/V pair
        len1 = min(length('visible'),length(varargin{index}));
        len2 = min(length('off'),length(varargin{index+1}));
        if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
            if strncmpi(varargin{index+1},'off',len2)
                gui_Visible = 'invisible';
                gui_VisibleInput = 'off';
            elseif strncmpi(varargin{index+1},'on',len2)
                gui_Visible = 'visible';
                gui_VisibleInput = 'on';
            end
        end
    end
    
    % Open fig file with stored settings.  Note: This executes all component
    % specific CreateFunctions with an empty HANDLES structure.

    
    % Do feval on layout code in m-file if it exists
    gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
    % this application data is used to indicate the running mode of a GUIDE
    % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
    % only used by actxproxy at this time.   
    setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1);
    if gui_Exported
        gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

        % make figure invisible here so that the visibility of figure is
        % consistent in OpeningFcn in the exported GUI case
        if isempty(gui_VisibleInput)
            gui_VisibleInput = get(gui_hFigure,'Visible');
        end
        set(gui_hFigure,'Visible','off')

        % openfig (called by local_openfig below) does this for guis without
        % the LayoutFcn. Be sure to do it here so guis show up on screen.
        movegui(gui_hFigure,'onscreen');
    else
        gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        % If the figure has InGUIInitialization it was not completely created
        % on the last pass.  Delete this handle and try again.
        if isappdata(gui_hFigure, 'InGUIInitialization')
            delete(gui_hFigure);
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
        end
    end
    if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]))
        rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]));
    end

    % Set flag to indicate starting GUI initialization
    setappdata(gui_hFigure,'InGUIInitialization',1);

    % Fetch GUIDE Application options
    gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
    % Singleton setting in the GUI M-file takes priority if different
    gui_Options.singleton = gui_State.gui_Singleton;

    if ~isappdata(gui_hFigure,'GUIOnScreen')
        % Adjust background color
        if gui_Options.syscolorfig
            set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
        end

        % Generate HANDLES structure and store with GUIDATA. If there is
        % user set GUI data already, keep that also.
        data = guidata(gui_hFigure);
        handles = guihandles(gui_hFigure);
        if ~isempty(handles)
            if isempty(data)
                data = handles;
            else
                names = fieldnames(handles);
                for k=1:length(names)
                    data.(char(names(k)))=handles.(char(names(k)));
                end
            end
        end
        guidata(gui_hFigure, data);
    end

    % Apply input P/V pairs other than 'visible'
    for index=1:2:length(varargin)
        if length(varargin) == index || ~ischar(varargin{index})
            break;
        end

        len1 = min(length('visible'),length(varargin{index}));
        if ~strncmpi(varargin{index},'visible',len1)
            try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end
        end
    end

    % If handle visibility is set to 'callback', turn it on until finished
    % with OpeningFcn
    gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
    if strcmp(gui_HandleVisibility, 'callback')
        set(gui_hFigure,'HandleVisibility', 'on');
    end

    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        % Handle the default callbacks of predefined toolbar tools in this
        % GUI, if any
        guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
        
        % Update handle visibility
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

        % Call openfig again to pick up the saved visibility or apply the
        % one passed in from the P/V pairs
        if ~gui_Exported
            gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
        elseif ~isempty(gui_VisibleInput)
            set(gui_hFigure,'Visible',gui_VisibleInput);
        end
        if strcmpi(get(gui_hFigure, 'Visible'), 'on')
            figure(gui_hFigure);
            
            if gui_Options.singleton
                setappdata(gui_hFigure,'GUIOnScreen', 1);
            end
        end

        % Done with GUI initialization
        if isappdata(gui_hFigure,'InGUIInitialization')
            rmappdata(gui_hFigure,'InGUIInitialization');
        end

        % If handle visibility is set to 'callback', turn it on until
        % finished with OutputFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end
        gui_Handles = guidata(gui_hFigure);
    else
        gui_Handles = [];
    end

    if nargout
        [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    else
        feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
    end

    if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
        set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

% openfig with three arguments was new from R13. Try to call that first, if
% failed, try the old openfig.
if nargin('openfig') == 2
    % OPENFIG did not accept 3rd input argument until R13,
    % toggle default figure visible to prevent the figure
    % from showing up too soon.
    gui_OldDefaultVisible = get(0,'defaultFigureVisible');
    set(0,'defaultFigureVisible','off');
    gui_hFigure = openfig(name, singleton);
    set(0,'defaultFigureVisible',gui_OldDefaultVisible);
else
    gui_hFigure = openfig(name, singleton, visible);
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)

try
    result = ispc && iscom(varargin{1}) ...
             && isequal(varargin{1},gcbo);
catch
    result = false;
end

function result = local_isInvokeHGCallback(gui_State, varargin)

try
    fhandle = functions(gui_State.gui_Callback);
    result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
             (ischar(varargin{1}) ...
             && isequal(ishghandle(varargin{2}), 1) ...
             && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                ~isempty(strfind(varargin{1}, '_CreateFcn'))) );
catch
    result = false;
end


